<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Articles/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Articles.Abstractions/Articles.Abstractions.csproj" />
  </ItemGroup>

</Project>
