<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Articles/" />
    <Folder Include="Articles/Behaviours/" />
    <Folder Include="Articles/Events/" />
    <Folder Include="Assets/Behaviours/" />
    <Folder Include="Assets/Enums/" />
    <Folder Include="Invitations/Behaviours/" />
    <Folder Include="Invitations/Enums/" />
    <Folder Include="Invitations/ValueObjects/" />
    <Folder Include="Reviewers/" />
    <Folder Include="Reviewers/Behaviours/" />
    <Folder Include="Reviewers/Events/" />
    <Folder Include="_Shared/" />
    <Folder Include="_Shared/Enums/" />
    <Folder Include="_Shared/ValueObjects/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/Articles.Abstractions/Articles.Abstractions.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Articles.GrpcContracts/Articles.GrpcContracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Blocks.Domain/Blocks.Domain.csproj" />
    <ProjectReference Include="../../../Modules/FileStorage/FileStorage.Contracts/FileStorage.Contracts.csproj" />
  </ItemGroup>

</Project>
