<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/Articles.Abstractions/Articles.Abstractions.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Articles.GrpcContracts/Articles.GrpcContracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Articles.IntegrationEvents.Contracts/Articles.IntegrationEvents.Contracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Blocks.EntityFramework/Blocks.EntityFrameworkCore.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Blocks.Exceptions/Blocks.Exceptions.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Blocks.MediatR/Blocks.MediatR.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Blocks.Messaging/Blocks.Messaging.csproj" />
    <ProjectReference Include="../../../Modules/FileStorage/FileStorage.Contracts/FileStorage.Contracts.csproj" />
    <ProjectReference Include="../../Auth/Auth.Domain/Auth.Domain.csproj" />
    <ProjectReference Include="../Submission.Domain/Submission.Domain.csproj" />
    <ProjectReference Include="../Submission.Persistence/Submission.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features/" />
    <Folder Include="Features/ApproveArticle/" />
    <Folder Include="Features/AssignAuthor/" />
    <Folder Include="Features/CreateAndAssignAuthor/" />
    <Folder Include="Features/CreateArticle/" />
    <Folder Include="Features/Shared/" />
    <Folder Include="Features/SubmitArticle/" />
    <Folder Include="Features/UploadFiles/" />
    <Folder Include="Features/UploadFiles/UploadManuscriptFile/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.10" />
  </ItemGroup>

</Project>
