<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/Articles.Abstractions/Articles.Abstractions.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Articles.Security/Articles.Security.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Articules.GrpcContracts/Articules.GrpcContracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Blocks.AspNetCore/Blocks.AspNetCore.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Blocks.Core/Blocks.Core.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Blocks.Exceptions/Blocks.Exceptions.csproj" />
    <ProjectReference Include="../Journals.Domain/Journals.Domain.csproj" />
    <ProjectReference Include="../Journals.Persistence/Journals.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features/Journals/Create/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.1.0" />
    <PackageReference Include="FastEndpoints.Swagger" Version="8.1.0" />
  </ItemGroup>

</Project>
