<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints.Swagger" Version="8.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Blocks.Core/Blocks.Core.csproj" />
    <ProjectReference Include="../Blocks.Domain/Blocks.Domain.csproj" />
  </ItemGroup>

</Project>
