<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Journals/" />
    <Folder Include="Journals/Enums/" />
    <Folder Include="Journals/Events/" />
    <Folder Include="Journals/ValueObjects/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/Blocks.Redis/Blocks.Redis.csproj" />
  </ItemGroup>

</Project>
