<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Articles/" />
    <Folder Include="Dtos/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/Articles.Abstractions/Articles.Abstractions.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Blocks.Domain/Blocks.Domain.csproj" />
  </ItemGroup>

</Project>
