<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/Articles.Abstractions/Articles.Abstractions.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Blocks.Messaging/Blocks.Messaging.csproj" />
    <ProjectReference Include="../../../Modules/FileStorage/FileStorage.Contracts/FileStorage.Contracts.csproj" />
    <ProjectReference Include="../Review.Domain/Review.Domain.csproj" />
    <ProjectReference Include="../Review.Persistence/Review.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features/" />
    <Folder Include="Features/Articles/" />
    <Folder Include="Features/Articles/InitialiseFromSubmission/" />
    <Folder Include="FileStorage/" />
  </ItemGroup>

</Project>
