<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Redis.OM" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Blocks.Exceptions/Blocks.Exceptions.csproj" />
  </ItemGroup>

</Project>
