<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/Articles.Security/Articles.Security.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Blocks.AspNetCore/Blocks.AspNetCore.csproj" />
    <ProjectReference Include="../Auth.Domain/Auth.Domain.csproj" />
    <ProjectReference Include="../Auth.Persistence/Auth.Persistence.csproj" />
  </ItemGroup>

</Project>
